name: flutter_proj_base
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.2.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  crypto: ^3.0.0
  flutter_hooks: ^0.20.5
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.5
  event_bus: ^2.0.1
  cupertino_icons: ^1.0.6
  uuid: ^3.0.1
  package_info_plus: ^8.0.0
  device_info_plus: ^9.1.1
  flutter_smart_dialog: ^4.7.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.0.8
  system_proxy: ^0.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dart_style: 2.3.3
  json_serializable: ^6.5.4
  build_runner: ^2.1.5
  freezed: ^2.2.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.2
flutter:
  uses-material-design: true
